#!/usr/bin/env python

# Copyright (c) The PyAMF Project.
# See LICENSE.txt for details.

# import ordering is important

import os.path
import platform
from enum import Enum
from os import environ

from setuptools import setup, find_packages

try:
    from Cython.Distutils import build_ext

    have_cython = True
except ImportError:
    from setuptools.command.build_ext import build_ext

    have_cython = False


from setuptools import Extension


version = (0, 8, 11)


class EnvConfig(Enum):
    """Custom environment flags and configuration values.

    When reading boolean values, the following values are considered truthy:

    - `true`
    - `yes`
    - `1`
    - `on`

    The evaluation is case-insensitive.

    """

    DISABLE_EXT = "PYAMF_DISABLE_EXT"
    """If set to truthy value, disables the building of the C extensions"""

    def read_from_env(self, fallback: bool = False) -> bool:
        return self.read_bool_like_val(self.value, fallback)

    @classmethod
    def read_bool_like_val(cls, key: str, fallback: bool = False) -> bool:
        val = environ.get(key)
        if val is None:
            return fallback
        val = val.lower()
        return val in ('true', 'yes', '1', 'on')


def setup_package():
    write_version_py()

    setup(
        version=get_version(),
        license=license,
        package_dir={"": "src"},
        packages=find_packages("src"),
        ext_modules=get_binary_extensions(),
        zip_safe=False,
        **extra_setup_args())



can_compile_extensions = have_cython and platform.python_implementation() == "CPython"


def get_binary_extensions() -> list[Extension]:

    if not can_compile_extensions or EnvConfig.DISABLE_EXT.read_from_env():
        return []

    extensions = [
        Extension(
            name="cpyamf.amf0",
            sources=["src/cpyamf/amf0.pyx"],
            include_dirs=["src"],
        ),
        Extension(
            name="cpyamf.amf3",
            sources=["src/cpyamf/amf3.pyx"],
            include_dirs=["src"],
        ),
        Extension(
            name="cpyamf.codec",
            sources=["src/cpyamf/codec.pyx"],
            include_dirs=["src"],
        ),
        Extension(
            name="cpyamf.util",
            sources=["src/cpyamf/util.pyx"],
            include_dirs=["src"],
        ),
    ]

    return extensions


def get_version():
    v = ''
    prev = None

    for x in version:
        if prev is not None:
            if isinstance(x, int):
                v += '.'

        prev = x
        v += str(x)

    return v.strip('.')


def get_package_data():
    return {
        'cpyamf': ['*.pxd'],
    }


def extra_setup_args():
    """
    Extra kwargs to supply in the call to C{setup}.

    This is used to supply custom commands, not metadata - that should live in
    setup.py itself.
    """
    return {
        'package_data': get_package_data(),
    }


def write_version_py(filename='src/pyamf/_version.py'):
    """
    """
    if os.path.exists(filename):
        os.remove(filename)

    content = """\
# THIS FILE IS GENERATED BY PYAMF SETUP.PY
from pyamf.versions import Version

version = Version(*%(version)r)
"""
    a = open(filename, 'wt')

    try:
        a.write(content % {'version': version})
    finally:
        a.close()


def read(fname):
    return open(os.path.join(os.path.dirname(__file__), fname)).read()


if __name__ == '__main__':
    setup_package()
